


SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS `WORKFLOWS` CASCADE
;

DROP TABLE IF EXISTS `WORKFLOW_TRANSITIONS` CASCADE
;

CREATE TABLE `WORKFLOWS` 
(
  `ID_WORKFLOW` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `OBJECT_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_WORKFLOW`)
);


CREATE TABLE `WORKFLOW_TRANSITIONS` 
(
  `ID_WORKFLOW_TRANSITION` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_WORKFLOW` bigint(20) NOT NULL,
  `ID_INITIAL_STATE` bigint(20) NOT NULL,
  `INITIAL_STATE` varchar(50) NOT NULL,
  `EVENT` varchar(50) NOT NULL,
  `GUARD` varchar(50) DEFAULT NULL,
  `ID_FINAL_STATE` bigint(20) NOT NULL,
  `FINAL_STATE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_WORKFLOW_TRANSITION`),
  KEY `IXFK_WORKFLOW_TRANSITIONS_WORKFLOWS` (`ID_WORKFLOW`),
  KEY `IXFK_WORKFLOW_TRANSITIONS_SYS_OPERATION_STATES_01` (`ID_INITIAL_STATE`),
  KEY `IXFK_WORKFLOW_TRANSITIONS_SYS_OPERATION_STATES_02` (`ID_FINAL_STATE`),
  CONSTRAINT `FK_WORKFLOW_TRANSITIONS_WORKFLOWS` FOREIGN KEY (`ID_WORKFLOW`) REFERENCES `WORKFLOWS` (`ID_WORKFLOW`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WORKFLOW_TRANSITIONS_SYS_OPERATION_STATES_01` FOREIGN KEY (`ID_INITIAL_STATE`) REFERENCES `SYS_OPERATION_STATES` (`ID_OPERATION_STATE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_WORKFLOW_TRANSITIONS_SYS_OPERATION_STATES_02` FOREIGN KEY (`ID_FINAL_STATE`) REFERENCES `SYS_OPERATION_STATES` (`ID_OPERATION_STATE`) ON DELETE NO ACTION ON UPDATE NO ACTION
);


-- kiosks operations workflow

insert into `WORKFLOWS` (`ID_WORKFLOW`,`NAME`,`OBJECT_NAME`) values (1, 'KIOSKS OPERATIONS WORKFLOW', 'KIOSK OPERATION');


insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evCapturingDocument',null,5002,'CAPTURING_DOCUMENT');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5002,'CAPTURING_DOCUMENT','evCapturedDocument',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5002,'CAPTURING_DOCUMENT','evCancel',null,5101,'INVALID_DOCUMENT');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evCapturingFingerprints',null,5004,'CAPTURING_FINGERPRINTS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5004,'CAPTURING_FINGERPRINTS','evCapturedFingerprints',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5004,'CAPTURING_FINGERPRINTS','evCancel',null,5102,'FINGERPRINTS_NOT_DETECTED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evCapturingPhoto',null,5006,'CAPTURING_PHOTO');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5006,'CAPTURING_PHOTO','evCapturedPhoto',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5006,'CAPTURING_PHOTO','evCancel',null,5103,'FACE_NOT_DETECTED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evRespondingQuestionary',null,5008,'RESPONDING_QUESTIONARY');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5008,'RESPONDING_QUESTIONARY','evRespondedQuestionary',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5008,'RESPONDING_QUESTIONARY','evCancel',null,5104,'EMPTY_QUESTIONARY');

--
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evChecking',null,5016,'CHECKING');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5016,'CHECKING','evChecked',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5016,'CHECKING','evCancel',null,5108,'INVALID_CHECKS');
--

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evPrinting',null,5010,'PRINTING');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5010,'PRINTING','evPrinted',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5010,'PRINTING','evCancel',null,5105,'INVALID_PRINTING');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evCorrect',null,5100,'TERMINATED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evIncorrect',null,5099,'ATTENDED_BOOTH');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5999,'PENDING_STEP','evCancel',null,5500,'CANCELLED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5099,'ATTENDED_BOOTH','evAccept',null,5100,'TERMINATED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1,5099,'ATTENDED_BOOTH','evReject',null,5100,'TERMINATED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1, 5999, 'PENDING_STEP', 'evCapturingIris', NULL, 5027, 'CAPTURING_IRIS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1, 5027, 'CAPTURING_IRIS', 'evCapturedIris', NULL, 5999, 'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1, 5027, 'CAPTURING_Iris', 'evCancel', NULL, 5028, 'IRIS_NOT_DETECTED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1, 5999, 'PENDING_STEP', 'evCapturingVerifyingIris', NULL, 5029, 'CAPTURING_VERIFYING_IRIS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1, 5029, 'CAPTURING_VERIFYING_IRIS', 'evCapturedVerifiedIris', NULL, 5999, 'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (1, 5029, 'CAPTURING_VERIFYNG_Iris', 'evCancel', NULL, 5028, 'IRIS_NOT_DETECTED');



-- Gates operations workflow

insert into `WORKFLOWS` (`ID_WORKFLOW`,`NAME`,`OBJECT_NAME`) values (2, 'GATES OPERATIONS WORKFLOW', 'GATE OPERATION');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCapturingDocument',null,5002,'CAPTURING_DOCUMENT');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5002,'CAPTURING_DOCUMENT','evCapturedDocument',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5002,'CAPTURING_DOCUMENT','evCancel',null,5101,'INVALID_DOCUMENT');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5002,'CAPTURING_DOCUMENT','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCapturingBoardingPass',null,5011,'CAPTURING_BOARDING_PASS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5011,'CAPTURING_BOARDING_PASS','evCapturedBoardingPass',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5011,'CAPTURING_BOARDING_PASS','evCancel',null,5106,'INVALID_BOARDING_PASS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5011,'CAPTURING_BOARDING_PASS','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evOpenEntryGate',null,5014,'ENTRY_GATE');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5014,'ENTRY_GATE','evCloseEntryGate',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5014,'ENTRY_GATE','evCancel',null,5107,'ENTRY_GATE_CANCELLED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5014,'ENTRY_GATE','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCapturingPhoto',null,5006,'CAPTURING_PHOTO');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5006,'CAPTURING_PHOTO','evCapturedPhoto',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5006,'CAPTURING_PHOTO','evCancel',null,5103,'FACE_NOT_DETECTED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5006,'CAPTURING_PHOTO','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evChecking',null,5016,'CHECKING');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5016,'CHECKING','evChecked',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5016,'CHECKING','evCancel',null,5108,'INVALID_CHECKS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5016,'CHECKING','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evOpenExitGate',null,5018,'EXIT_GATE');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5018,'EXIT_GATE','evCloseExitGate',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5018,'EXIT_GATE','evCancel',null,5109,'EXIT_GATE_CANCELLED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5018,'EXIT_GATE','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCorrect',null,5100,'TERMINATED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evIncorrect',null,5099,'ATTENDED_BOOTH');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCancel',null,5500,'CANCELLED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5099,'ATTENDED_BOOTH','evOpenExitGate',null,5099,'ATTENDED_BOOTH');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5099,'ATTENDED_BOOTH','evCloseExitGate',null,5099,'ATTENDED_BOOTH');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5099,'ATTENDED_BOOTH','evCancel',null,5109,'EXIT_GATE_CANCELLED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5099,'ATTENDED_BOOTH','evAccept',null,5100,'TERMINATED');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5099,'ATTENDED_BOOTH','evReject',null,5100,'TERMINATED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCapturingBarcode',null,5020,'CAPTURING_BARCODE');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5020,'CAPTURING_BARCODE','evCapturedBarcode',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5020,'CAPTURING_BARCODE','evCancel',null,5101,'INVALID_DOCUMENT');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5020,'CAPTURING_BARCODE','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCheckingSerpro',null,5021,'CHECKING_SERPRO');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5021,'CHECKING_SERPRO','evCheckedSerpro',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5021,'CHECKING_SERPRO','evCancel',null,5108,'INVALID_CHECKS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5021,'CHECKING_SERPRO','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evGeneratingQR',null,5022,'GENERATING_QR');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5022,'GENERATING_QR','evGeneratedQR',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5022,'GENERATING_QR','evCancel',null,5108,'INVALID_CHECKS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5022,'GENERATING_QR','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5999,'PENDING_STEP','evCapturingQR',null,5026,'CAPTURING_QR');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5026,'CAPTURING_QR','evCapturedQR',null,5999,'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5026,'CAPTURING_QR','evCancel',null,5101,'INVALID_DOCUMENT');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2,5026,'CAPTURING_QR','evCancelByUser',null,5501,'CANCELLED_BY_USER');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2, 5999, 'PENDING_STEP', 'evCapturingIris', NULL, 5027, 'CAPTURING_IRIS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2, 5027, 'CAPTURING_IRIS', 'evCapturedIris', NULL, 5999, 'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2, 5027, 'CAPTURING_Iris', 'evCancel', NULL, 5028, 'IRIS_NOT_DETECTED');

insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2, 5999, 'PENDING_STEP', 'evCapturingVerifyingIris', NULL, 5029, 'CAPTURING_VERIFYING_IRIS');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2, 5029, 'CAPTURING_VERIFYING_IRIS', 'evCapturedVerifiedIris', NULL, 5999, 'PENDING_STEP');
insert into `WORKFLOW_TRANSITIONS`(`ID_WORKFLOW`,`ID_INITIAL_STATE`,`INITIAL_STATE`,`EVENT`,`GUARD`,`ID_FINAL_STATE`,`FINAL_STATE`) values (2, 5029, 'CAPTURING_VERIFYNG_Iris', 'evCancel', NULL, 5028, 'IRIS_NOT_DETECTED');


SET FOREIGN_KEY_CHECKS = 1;


